name: CI-EXAMPLE

on:
  push:
    branches:
      - master
    paths:
      - 'KakaoLoginExample/**'

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./KakaoLoginExample

    steps:
    - uses: actions/checkout@v2

    - name: Yarn
      run: yarn

    - name: Lint
      run: yarn lint

    # - name: Build TSC
    #   run: yarn tsc

    - name: Test
      run: yarn test --coverage
